name: components
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - pyyaml
  - hydra-core=1.3.2
  - pip=24.3.1
  - scipy=1.16.1
  - numpy=2.3.5
  - pip:
      - mlflow==3.3.2
      - wandb==0.22.0
      - databricks_cli==0.8.7
